In [1]:
import pandas as pd

In [2]:
listings = pd.read_csv('listings.csv')
listings_ = pd.read_csv('listings.csv.gz')
neighbor = pd.read_csv('neighbourhoods.csv')
reviews = pd.read_csv('reviews.csv')

In [4]:
listings

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,175,30,48,2019-11-04,0.36,2,365
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,74,1,375,2020-11-22,4.97,1,307
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,30,50,2019-12-02,0.36,1,365
3,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Midtown,40.76468,-73.98315,Private room,65,2,474,2020-09-25,3.36,1,0
4,5203,Cozy Clean Guest Room - Family Apt,7490,MaryEllen,Manhattan,Upper West Side,40.80178,-73.96723,Private room,75,2,118,2017-07-21,0.86,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36918,46937371,Gramercy Loft-Studio/Prime Location ~W&D in unit~,27181542,Jt,Manhattan,Kips Bay,40.73961,-73.97971,Entire home/apt,199,30,0,NaN,NaN,15,180
36919,46937954,Upper West Side Penthouse- Terrace & Hidden Ga...,287807769,Allen,Manhattan,Upper West Side,40.78061,-73.98514,Entire home/apt,205,30,0,NaN,NaN,1,83
36920,46938514,Cozy shared room in East Harlem,303319010,Naiomy,Manhattan,East Harlem,40.80054,-73.93340,Shared room,35,1,0,NaN,NaN,1,176
36921,46938537,Boho Chic Rhapsody in New York City,3351317,Clara,Manhattan,Kips Bay,40.74033,-73.98242,Entire home/apt,295,4,0,NaN,NaN,3,83
36922,46941857,Modern 4 Bed W/ 5 Bath with Backyard Access,13603829,Kay,Brooklyn,Bushwick,40.69648,-73.92707,Entire home/apt,500,1,0,NaN,NaN,7,354

In [10]:
listings_

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2595,https://www.airbnb.com/rooms/2595,20201210194816,2020-12-11,Skylit Midtown Castle,"Beautiful, spacious skylit studio in the heart...",Centrally located in the heart of Manhattan ju...,https://a0.muscache.com/pictures/f0813a11-40b2...,2845,https://www.airbnb.com/users/show/2845,...,10.0,10.0,9.0,NaN,f,2,2,0,0,0.36
1,3831,https://www.airbnb.com/rooms/3831,20201210194816,2020-12-11,"Whole flr w/private bdrm, bath & kitchen(pls r...","Enjoy 500 s.f. top floor in 1899 brownstone, w...",Just the right mix of urban center and local n...,https://a0.muscache.com/pictures/e49999c2-9fd5...,4869,https://www.airbnb.com/users/show/4869,...,9.0,10.0,10.0,NaN,f,1,1,0,0,4.97
2,5121,https://www.airbnb.com/rooms/5121,20201210194816,2020-12-11,BlissArtsSpace!,<b>The space</b><br />HELLO EVERYONE AND THANK...,NaN,https://a0.muscache.com/pictures/2090980c-b68e...,7356,https://www.airbnb.com/users/show/7356,...,10.0,9.0,9.0,NaN,f,1,0,1,0,0.36
3,5178,https://www.airbnb.com/rooms/5178,20201210194816,2020-12-11,Large Furnished Room Near B'way,Please don’t expect the luxury here just a bas...,"Theater district, many restaurants around here.",https://a0.muscache.com/pictures/12065/f070997...,8967,https://www.airbnb.com/users/show/8967,...,9.0,10.0,9.0,NaN,f,1,0,1,0,3.36
4,5203,https://www.airbnb.com/rooms/5203,20201210194816,2020-12-11,Cozy Clean Guest Room - Family Apt,"Our best guests are seeking a safe, clean, spa...",Our neighborhood is full of restaurants and ca...,https://a0.muscache.com/pictures/103776/b37157...,7490,https://www.airbnb.com/users/show/7490,...,10.0,10.0,10.0,NaN,f,1,0,1,0,0.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36918,46937371,https://www.airbnb.com/rooms/46937371,20201210194816,2020-12-11,Gramercy Loft-Studio/Prime Location ~W&D in unit~,This AMAZING ALL Brand NEW **5 Star quality** ...,The apartment is very centrally located in the...,https://a0.muscache.com/pictures/a70776a5-f510...,27181542,https://www.airbnb.com/users/show/27181542,...,NaN,NaN,NaN,NaN,f,15,15,0,0,NaN
36919,46937954,https://www.airbnb.com/rooms/46937954,20201210194816,2020-12-11,Upper West Side Penthouse- Terrace & Hidden Ga...,"Bright, sunny and well-maintained Penthouse wi...",Enjoy your visit in one of the greenest parts ...,https://a0.muscache.com/pictures/5962e4a1-a1a9...,287807769,https://www.airbnb.com/users/show/287807769,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
36920,46938514,https://www.airbnb.com/rooms/46938514,20201210194816,2020-12-11,Cozy shared room in East Harlem,"""Common area with twin day bed in the ""El Ba...",NaN,https://a0.muscache.com/pictures/94c199b0-5262...,303319010,https://www.airbnb.com/users/show/303319010,...,NaN,NaN,NaN,NaN,f,1,0,0,1,NaN
36921,46938537,https://www.airbnb.com/rooms/46938537,20201210194816,2020-12-11,Boho Chic Rhapsody in New York City,"Open, loft-like an one bedroom in a historic b...",NaN,https://a0.muscache.com/pictures/63174244/283c...,3351317,https://www.airbnb.com/users/show/3351317,...,NaN,NaN,NaN,NaN,f,3,3,0,0,NaN
36922,46941857,https://www.airbnb.com/rooms/46941857,20201210194816,2020-12-11,Modern 4 Bed W/ 5 Bath with Backyard Access,This modern luxurious townhome is nestled on a...,NaN,https://a0.muscache.com/pictures/488aaa9e-0e29...,13603829,https://www.airbnb.com/users/show/13603829,...,NaN,NaN,NaN,NaN,f,7,7,0,0,NaN

In [11]:
listings_.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'description',
       'neighborhood_overview', 'picture_url', 'host_id', 'host_url',
       'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [14]:
# 

host_cols = ['id', 'host_id', 'host_url',
       'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified','calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms']
host_in_listings_ = listings_[host_cols]
host_in_listings_

,id,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,...,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
0,2595,2845,https://www.airbnb.com/users/show/2845,Jennifer,2008-09-09,"New York, New York, United States",A New Yorker since 2000! My passion is creatin...,within a few hours,92%,25%,...,Midtown,6.0,6.0,"['email', 'phone', 'reviews', 'offline_governm...",t,t,2,2,0,0
1,3831,4869,https://www.airbnb.com/users/show/4869,LisaRoxanne,2008-12-07,"New York, New York, United States",Laid-back Native New Yorker (formerly bi-coast...,within an hour,95%,93%,...,Clinton Hill,1.0,1.0,"['email', 'phone', 'reviews', 'offline_governm...",t,t,1,1,0,0
2,5121,7356,https://www.airbnb.com/users/show/7356,Garon,2009-02-03,"New York, New York, United States","I am an artist(painter, filmmaker) and curato...",NaN,NaN,NaN,...,Bedford-Stuyvesant,1.0,1.0,"['email', 'phone', 'facebook', 'reviews', 'off...",t,t,1,0,1,0
3,5178,8967,https://www.airbnb.com/users/show/8967,Shunichi,2009-03-03,"New York, New York, United States",I used to work for a financial industry but no...,within a day,100%,100%,...,Hell's Kitchen,1.0,1.0,"['email', 'phone', 'facebook', 'reviews']",t,f,1,0,1,0
4,5203,7490,https://www.airbnb.com/users/show/7490,MaryEllen,2009-02-05,"New York, New York, United States",Welcome to family life with my oldest two away...,NaN,NaN,NaN,...,Upper West Side,1.0,1.0,"['email', 'phone', 'facebook', 'google', 'revi...",t,t,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36918,46937371,27181542,https://www.airbnb.com/users/show/27181542,Jt,2015-02-03,"New York, New York, United States",I moved to New York about 14 years ago and I c...,within an hour,100%,100%,...,Upper East Side,10.0,10.0,"['email', 'phone', 'reviews', 'offline_governm...",t,t,15,15,0,0
36919,46937954,287807769,https://www.airbnb.com/users/show/287807769,Allen,2019-08-21,"New York, New York, United States",NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,"['email', 'phone', 'offline_government_id', 'g...",t,t,1,1,0,0
36920,46938514,303319010,https://www.airbnb.com/users/show/303319010,Naiomy,2019-10-19,"New York, New York, United States",NaN,NaN,NaN,100%,...,NaN,0.0,0.0,"['email', 'phone', 'offline_government_id', 's...",t,t,1,0,0,1
36921,46938537,3351317,https://www.airbnb.com/users/show/3351317,Clara,2012-08-23,"New York, New York, United States","love music, art and traveling around the world",within a few hours,100%,100%,...,Kips Bay,1.0,1.0,"['email', 'phone', 'reviews', 'offline_governm...",t,t,3,3,0,0
36922,46941857,13603829,https://www.airbnb.com/users/show/13603829,Kay,2014-03-27,"New York, New York, United States","Traveler, Entrepreneur, Artist",within an hour,98%,93%,...,Kensington,5.0,5.0,"['email', 'phone', 'reviews', 'offline_governm...",t,t,7,7,0,0

In [6]:
neighbor

    neighbourhood_group  neighbourhood
0                 Bronx       Allerton
1                 Bronx     Baychester
2                 Bronx        Belmont
3                 Bronx      Bronxdale
4                 Bronx    Castle Hill
..                  ...            ...
225       Staten Island    Tottenville
226       Staten Island  West Brighton
227       Staten Island    Westerleigh
228       Staten Island    Willowbrook
229       Staten Island        Woodrow

[230 rows x 2 columns]

In [8]:
reviews

        listing_id        date
0             2595  2009-11-21
1             2595  2009-12-05
2             2595  2009-12-10
3             2595  2010-04-09
4             2595  2010-05-25
...            ...         ...
855955    46814801  2020-12-06
855956    46829853  2020-12-06
855957    46837690  2020-12-07
855958    46838499  2020-12-09
855959    46877998  2020-12-09

[855960 rows x 2 columns]